name: t22-wed-mor-geophysics
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - numpy==1.22.*
  - scipy==1.8.*
  - matplotlib==3.5.*
  - xarray==2022.3.*
  - netcdf4==1.5.*
  - libnetcdf==4.8.*
  - jupyter==1.0.*
  - jupyterlab==3.3.*
  - ipykernel==6.13.*
  - numba==0.53.*
  - pykdtree==1.3.*
  - pyproj==3.2.*
  - proj==8.1.*
  - pygmt==0.6.*
  - gmt==6.3.*
  - verde==1.7.*
  - pooch==1.6.*
  - boule==0.3.*
